//! MCP (Model Context Protocol) server for Thurbox.
//!
//! Provides programmatic access to Thurbox configuration — projects, roles,
//! and session listing — so external agents can set up workspaces without
//! manual TUI interaction.

mod tools;
pub mod types;

use std::path::{Path, PathBuf};
use std::sync::Mutex;

use rmcp::handler::server::router::tool::ToolRouter;
use rmcp::model::{ServerCapabilities, ServerInfo};
use rmcp::{tool_handler, ServerHandler};

use crate::storage::Database;

/// MCP server backed by the shared Thurbox SQLite database.
pub struct ThurboxMcp {
    /// Database handle wrapped in std::sync::Mutex (rusqlite is !Send).
    db: Mutex<Database>,
    /// Path to the SQLite database (needed for tmux scheduled command dispatch).
    db_path: PathBuf,
    /// Tool router generated by the `#[tool_router]` macro.
    tool_router: ToolRouter<ThurboxMcp>,
}

impl ThurboxMcp {
    /// Create a new MCP server connected to the database at `db_path`.
    pub fn new(db_path: &Path) -> anyhow::Result<Self> {
        let db = Database::open(db_path)?;
        Ok(Self {
            db: Mutex::new(db),
            db_path: db_path.to_path_buf(),
            tool_router: Self::tool_router(),
        })
    }
}

#[tool_handler]
impl ServerHandler for ThurboxMcp {
    fn get_info(&self) -> ServerInfo {
        ServerInfo {
            instructions: Some(
                "Thurbox MCP server — manage projects, roles, and list sessions.".to_string(),
            ),
            capabilities: ServerCapabilities::builder().enable_tools().build(),
            ..Default::default()
        }
    }
}
